### ISSUE TITLE
CheckStatus query?

### ISSUE THREAD

**Issue by thbar** [grutts/siri#1]
Hi!

I just stumbled upon your library, thanks for sharing it!

I would have used it today for `CheckStatus`, but it is not apparently available.

Would it make sense to add it as a possibility?

I find it useful to verify the validity of a given connection.

Thanks!

**Comment by grutts** [comment]
Hi @thbar, could `CheckStatusRequest` be what you're looking for? https://github.com/grutts/siri/blob/c388c209d1c803be166e767d5aa53a93a34c002d/siri/__init__.py#L25

**Comment by thbar** [comment]
@grutts I think it is exactly that! Let me know if I can help as well (I can do testing etc).

Also, I am interested to get in touch with you (privately if you prefer) to understand how you use SIRI in your company (I work on the French NAP at https://transport.data.gouv.fr/?locale=en), if you use subscription or requests etc. My email is on my GitHub profile. Thanks for considering this!

**Comment by grutts** [comment]
I think it should already work out of the box, without any further changes. Something like 

```
siri_obj = Siri(check_status_request=CheckStatusRequest(...))
```

Am I missing something?

Sure, I'll drop you an email.

**Comment by thbar** [comment]
Ahh I think I didn't detect that possibility for some reason. I'll give it a shot and will report back. Many thanks!

(thanks for your email!)

**Comment by grutts** [comment]
Ok nice! I'll close this for now, please re-open if that doesn't resolve the issue
